version: "3"

services:
  nginx:
    build: ./docker-images/nginx-custom
    container_name: nginx
    restart: unless-stopped
    tty: true
    environment:
      DOMAINS: ""
      # DOMAINS: "rnd.4experience.co"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-images/nginx-custom/conf:/etc/nginx/available-confs
      - ./docker-images/nginx-custom/snippets:/etc/nginx/snippets
      - ./www/:/var/www
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/self-signed:/etc/self-signed
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
